spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    driverClass:  com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
    showSql:  true

  rabbitmq:
    host: 192.168.0.86
    port: 5672
    username: admin
    password: 123456



