spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    driverClass:  com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
    showSql:  true

  redis:
    database: 0
    host: 192.168.5.136
    port: 6379
    password:
    pool:
      maxActive: 8
      maxWait: -1
      maxIdle: 8
      minIdle: 0
    timeout:  6000



